---
- hosts: all

  roles:
    - role: common
    - role: gantsign.java
      java_version: '9'
      java_license_declaration: 'I accept the "Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX" under the terms at http://www.oracle.com/technetwork/java/javase/terms/license/index.html'
    - role: gantsign.maven
    # - role: gantsign.intellij #https://galaxy.ansible.com/gantsign/intellij/
    #   intellij_version: '2017.3'
    #   intellij_edition: ultimate
    #   intellij_license_key_path: '/ansible/idea.key'
    #   users:
    #     - username: jesse
    - role: gantsign.oh-my-zsh
      users:
        - username: jesse
          oh_my_zsh:
            plugins:
              - git
              - docker
              - mvn
              - extract
              - sudo
              - ubuntu
              - z
    - role: cmprescott.chrome
      become: yes
    - role: gantsign.postman
    - role: tersmitten.sudoers
    - role: finalize
  vars:
    email: bekkum@gmail.com
    ansible_become: true
    playbook_filename: dev3.yml
    ssh_key_comment: bekkum@gmail.com (dev)
    sudoers_sudoers:
      defaults:
        - env_reset
        - exempt_group=sudo
        - secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      privileges:
        - name: root
          entry: "ALL=(ALL:ALL) ALL"
        - name: "%admin"
          entry: "ALL=(ALL) ALL"
        - name: "%sudo"
          entry: "ALL=NOPASSWD:ALL"
  remote_user: root
