---
- include: get_key.yml

- name: add google cloud key to apt-key
  apt_key: file=/root/A7317B0F.gpg
  sudo: yes

- name: sources.list
  template: >
    src=google-cloud-sdk.list.j2
    dest=/etc/apt/sources.list.d/google-cloud-sdk.list
    force=no
  register: sources_list_result
  sudo: yes

# Install apt-transport-https
- name: install apt-transport-https
  action: "{{backcompat_pkg_mgr}} name=apt-transport-https"
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
