---
- name: repo
  template: >
    src=google-cloud-sdk.repo.j2
    dest=/etc/yum.repos.d/google-cloud-sdk.repo
    force=no
  sudo: yes

# Uncertain which ones of these work per
# https://github.com/ansible/ansible/issues/20711

#- name: install signing keys
#  rpm_key:
#    key: "{{item}}"
#    state: present
#  sudo: yes
#  with_items:
#    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
#    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#
#- name: install signing keys
#  rpm_key:
#    key: "{{item}}"
#    state: present
#  with_items:
#    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
#    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
