- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
  become: true

- name: Create user jesse
  user:
    name: jesse
    comment: "Jesse van Bekkum"
    shell: /bin/zsh
    state: present
    createhome: yes
    generate_ssh_key: yes
    ssh_key_comment: "{{ssh_key_comment}}"
  become: true  
