---
# file: tasks/install.yml
# Top-level installer for Oracle JDK.
#

- name: get JDK tarball (as tar.gz file)
  get_url:
    url:     "{{ jdk_tarball_url }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest:    "{{ java_download_path }}/java.tar.gz"

- name: mkdir for Java
  file:
    path: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,go=rx"

- name: install JDK via tarball file
  unarchive:
    src: "{{ java_download_path }}/java.tar.gz"
    dest: "{{ java_install_dir }}"
    owner: root
    group: root
    mode: "go-w"
    copy: no

- name: Set JAVA_HOME as environment variable
  become: true
  lineinfile:
    path: /etc/environment
    line: "JAVA_HOME={{ java_install_dir }}/{{ java_default_link_name }}"



    # No link creation is necessary on Mac OS X --
    # the package installer automatically creates symlinks in /usr/bin.

- name: link "{{ java_install_dir }}/{{ java_default_link_name }}"
  file:
    dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
    src: "{{ java_install_dir }}/jdk-9"
    state: link
  when: java_version == 9

- name: link "{{ java_install_dir }}/{{ java_default_link_name }}"
  file:
    dest: "{{ java_install_dir }}/{{ java_default_link_name }}"
    src: "{{ java_install_dir }}/jdk{{ jdk_version }}"
    state: link
  when: java_version == 8

- name: alternatives link for "java"
  alternatives:
    name: java
    link: /usr/bin/java
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/java"

- name: alternatives link for "javac"
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/javac"

- name: alternatives link for "jar"
  alternatives:
    name: jar
    link: /usr/bin/jar
    path: "{{ java_install_dir }}/{{ java_default_link_name }}/bin/jar"

- name: check if "java_sdk" target exists
  stat: path=/usr/lib/jvm/java
  register: filecheck

- name: alternatives link for "java_sdk"
  alternatives:
    name: java_sdk
    link: /usr/lib/jvm/java
    path: "{{ java_install_dir }}/{{ java_default_link_name }}"
  when: filecheck and filecheck.stat.exists

- name: remove temporary downloaded files, if requested
  file: path={{ item }} state=absent
  with_items:
    - "{{ java_download_path }}/java.tar.gz"
    - "{{ java_download_path }}/check-tarball-installed.sh"
  ignore_errors: true
  when: java_remove_download
