---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#


- name: Set jdk_version (8)
  set_fact:
    jdk_version: "1.{{ java_version }}.0_{{ java_subversion }}"
  when: java_version == 8

- name: Set jdk_version (9)
  set_fact:
    jdk_version: "9"
  when: java_version == 9


#
# platform-specific variables
#

- name: set java architecture
  set_fact:
    jdk_arch: "{{ 'i586'  if ansible_architecture == 'i386' else 'x64' }}"

- name: set java OS for Linux
  set_fact:
    jdk_os: linux
  when: ansible_system == 'Linux'

- name: compose filename, if necessary
  set_fact:
    jdk_tarball_file: "jdk-{{ java_version }}u{{ java_subversion }}-{{ jdk_os }}-{{ jdk_arch }}"
  when: jdk_tarball_file is not defined

- name: compose url for downloading file, if necessary
  set_fact:
    jdk_tarball_url:  "http://download.oracle.com/otn-pub/java/jdk/{{ jdk_version_detail }}/{{ jdk_tarball_file }}"
  when: jdk_version_detail is defined


#
# JCE variables
#

- name: set JCE variables for java 8
  set_fact:
    jce_zip_file:   "jce_policy-{{ java_version }}.zip"
    jce_zip_folder: "UnlimitedJCEPolicyJDK{{ java_version }}"
  when: java_version == 8

- name: set JCE download file
  set_fact:
    jce_zip_url: "http://download.oracle.com/otn-pub/java/jce/{{ java_version }}/{{ jce_zip_file }}"
  when: java_version == 8

#
# directories
#

- name: set java installation directory on Debian platforms
  set_fact:
    java_install_dir: /usr/lib/jvm
    java_default_link_name: default-java
    java_home: /usr/lib/jvm/default-java
  when: ansible_os_family == "Debian"
