---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: true

- name: Make sure we have a 'jesse' group
  group:
    name: jesse
    state: present
  become: true

# - name: Allow 'wheel' group to have passwordless sudo
#   lineinfile:
#     dest: /etc/sudoers
#     state: present
#     regexp: '^%wheel'
#     line: '%wheel ALL=(ALL) NOPASSWD: ALL'
#   become: true

- name: Create user jesse
  user:
    name: jesse
    comment: "Jesse van Bekkum"
    shell: /bin/zsh
    groups: "jesse, users, sudo"
    state: present
    createhome: yes
    password: $6$opHS.cyl7NrRQ1$koNiPlU23GInqcwArgLh55oHF.JjJ0FSxfLxnVc.gJ16XPyYm8cFlwDFaRIYZykV8fTV4AFsFqmi41vK8bzXu/
    skeleton: yes
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_comment: "{{ssh_key_comment}}"
  become: true
