---
- name: Install list of packages
  apt: name={{item}} state=installed update_cache=true
  become: true
  with_items:
    - docker-ce
    - docker-compose

- name: Add jesse to the docker group
  become: true
  user:
    name: jesse
    groups: docker
    append: yes
